// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2C-EzGQ8WAxNmGI2CCTx8XgrRt4vHK_w',
    appId: '1:903114157677:web:c5ced7f6a24b9cc7e81964',
    messagingSenderId: '903114157677',
    projectId: 'fir-auth-project-c1f51',
    authDomain: 'fir-auth-project-c1f51.firebaseapp.com',
    storageBucket: 'fir-auth-project-c1f51.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8qp4fSyg4xFkJOX9UEi2FfX9Q7yQANok',
    appId: '1:903114157677:android:6c4af84b83867a8ce81964',
    messagingSenderId: '903114157677',
    projectId: 'fir-auth-project-c1f51',
    storageBucket: 'fir-auth-project-c1f51.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAB76wWSyb9aSb44HEzKs0hjyU3ELiudM',
    appId: '1:903114157677:ios:1c0b306878307254e81964',
    messagingSenderId: '903114157677',
    projectId: 'fir-auth-project-c1f51',
    storageBucket: 'fir-auth-project-c1f51.appspot.com',
    iosClientId: '903114157677-ag76f5t9abkmth9jde6qkfnvaigh19lk.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseAuthApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAB76wWSyb9aSb44HEzKs0hjyU3ELiudM',
    appId: '1:903114157677:ios:1c0b306878307254e81964',
    messagingSenderId: '903114157677',
    projectId: 'fir-auth-project-c1f51',
    storageBucket: 'fir-auth-project-c1f51.appspot.com',
    iosClientId: '903114157677-ag76f5t9abkmth9jde6qkfnvaigh19lk.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseAuthApp',
  );
}